from patient import Patient
from admin import Admin
from clinic import Clinic
from line import Line
from medic import Medic
from appointment import Appointment
from token import Token
from ptoken import PToken
from pnotification import PNotification
from anotification import ANotification