from patient import PatientViewSet
from admin import AdminViewSet
from clinic import ClinicViewSet
from line import LineViewSet
from medic import MedicViewSet
from appointment import AppointViewSet
from token import TokenViewSet
from ptoken import PTokenViewSet
from adminAuthentication import adminLogin
from adminAuthentication import adminLogout
from adminAuthentication import check
from patientAuthentication import patientLogin
from patientAuthentication import patientLogout
from patientAuthentication import pcheck
from pnotification import PNotificationViewSet
from anotification import ANotificationViewSet
from restricted import restricted