from patient import PatientSerializer
from admin import AdminSerializer
from clinic import ClinicSerializer
from line import LineSerializer
from medic import MedicSerializer
from appointment import AppointSerializer
from token import TokenSerializer
from ptoken import PTokenSerializer
from pnotification import PNotificationSerializer
from anotification import ANotificationSerializer